### ISSUE TITLE
issue with compiling

### ISSUE THREAD

**Issue by GGC14Postal** [yusufsahinhamza/darkorbit-emulators#3]
the console is starting and just shutdowns after trying to start

Output Visual Studio:
"DarkOrbit.exe" (CLR v4.0.30319: DarkOrbit.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
Das Programm "[18784] DarkOrbit.exe" wurde mit Code 0 (0x0) beendet.

Output Log

[10.03.2021 01: 10:37] - [Program.cs] Main void exception: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: {. Path '[4]', line 1, position 832.
   bei Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   bei Ow.Managers.QueryManager.LoadMaps() in C:\Users\\QueryManager.cs:Zeile 316.
   bei Ow.Program.LoadDatabase() in C:\Users\\Program.cs:Zeile 85.
   bei Ow.Program.Main(String[] args) in C:\Users\\Program.cs:Zeile 32.

**Comment by yusufsahinhamza** [comment]
@GGC14Postal Hello, looks like something wrong with json deserialization, potentially from database. Check the jsons in database especially in `server_maps` table.
