### ISSUE TITLE
Please, help 

### ISSUE THREAD

**Issue by Takiusu** [yusufsahinhamza/darkorbit-emulators#4]
Hello, sorry for disturbance,  i need a help with emulator. I want to play Dark Orbit offline. Please, contact me.

**Comment by yusufsahinhamza** [comment]
@Rayvakarian You can play it offline as well, just set everything up and there you go.

**Comment by Rayvakarian** [comment]
Sorry, we don't know how. I asked my friend, even he doesn't know. Can you contact us, please?

**Comment by Takiusu** [comment]
Hello! This is a message from Ray's friend. I'm echomokona (in github), and I'm trying to figure out and learn how to set the game up - both server (using your emulator), and client (no idea how!). I have never played Dark Orbit before and thus have 0 familiarity with the game - Ray's the one who played the game. 
Allow me to ask, please: Can you write a quick guide for us, covering how to set the server + database, and how to get a client that works with this server? Thank you very much!

**Comment by yusufsahinhamza** [comment]
@Rayvakarian Hello, it's very simple, clone [darkorbit-cms](https://github.com/yusufsahinhamza/darkorbit-cms) repository and put it into an apache server (people are generally using xampp). Make sure you created a database and imported `server.sql` as well. Then clone this repository and open it with **Visual Studio**, then you should be able to run the emulator and game should work. If that's not enough, please check the second page in elitepvpers forum, there is a video that shows how to build the game, it's made by community.

**Comment by Takiusu** [comment]
Thank you very much, mr. Yusuf! I'll be setting it up for Ray and after I'm done we are going to report results. These instructions are clear (and, good sir, you are fast!) and accurate! Have a wonderful night, and know you have really brought joy to someone.

**Comment by Takiusu** [comment]
Hello! It's Ray. We have a success with emulator, it's working well, which cannot be said about the client - i tried to launch it through the web browser, but he shows only text, without images, reigistration and log in is not working, nothing happens when we try to register / login

**Comment by yusufsahinhamza** [comment]
@Rayvakarian Make sure you imported the database and check settings at `/files/config.php` in [darkorbit-cms](https://github.com/yusufsahinhamza/darkorbit-cms). Other than that i'm not really sure and it's hard for me to know the problem like that.

**Comment by Rayvakarian** [comment]
Thank you, i resolved a problem, now client asking for Adobe flash player, but he's not working.

**Comment by Takiusu** [comment]
Greetings! It's us again, Ray and echomokona! As promised, we're reporting our progress on getting DarkOrbit running, both server and client-side. 

After a bit of tinkering around to make the database and the client work correctly, we have stumbled upon a predictable problem. 
One neither me nor Ray have yet learned how to deal with. Microsoft has rolled the Flash-killer update and our computers already have got it. And it's the first time I have needed Flash for anything in almost a decade.

So, the game client is unable to run from browser: 'Get the Adobe Flash Player. In order to play DarkOrbit, you need the latest version of Flash[.....]. 
Please, can you provide us with instructions on how to get past this point?

Kind regards, and big thanks!
~ rayvakarian & echomokona

**Comment by yusufsahinhamza** [comment]
@Rayvakarian Hello, as you can see here: https://www.adobe.com/products/flashplayer/end-of-life.html, browsers etc. and Adobe itself is not supporting Flash Player anymore so you won't be able to play in browser. Instead you may want to check downloadable clients that comes with embedded Flash Player and make a connection between this emulator and the client. I'm also no longer working on this project and i guess if you're done with installing, i can close the issue, thank you.
